import PostForm from "@components/screens/home/post-form";
import PostList from "@components/screens/home/post-list";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-xl mx-auto">
        <PostForm />
        <PostList />
      </div>
    </>
  );
};

export default Home;
