import PostList from "@components/screens/home/post-list";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-xl mx-auto">
        <div className="my-6">
          <Link href={`/post/create`}>
            <a className="text-white bg-green-500 p-2 rounded-md">
              Create Post
            </a>
          </Link>
        </div>
        <PostList />
      </div>
    </>
  );
};

export default Home;
